name: Create Progress File

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/2 * * * *' # Run every 2 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List files in the repository
        run: ls -la

      - name: Run Python Script
        run: python Github_Sheet_update.py

